apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metricflow-db
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: metricflow-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: ${SECRET_ARN}
        property: password
    
    - secretKey: DB_USER
      remoteRef:
        key: ${SECRET_ARN}
        property: username