apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metricflow-db
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: metricflow-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: arn:aws:secretsmanager:us-east-2:333207082767:secret:rds!db-7a7c21f4-c293-4df9-8715-63e83bc0bba7-NBYJIO
        property: password
    
    - secretKey: DB_USER
      remoteRef:
        key: arn:aws:secretsmanager:us-east-2:333207082767:secret:rds!db-7a7c21f4-c293-4df9-8715-63e83bc0bba7-NBYJIO
        property: username