apiVersion: v1
kind: Secret
metadata:
  name: metricflow-secret
  labels: 
    app.kubernetes.io/name: metricflow
    app.kubernetes.io/component: api
type: Opaque
stringData:
  DB_NAME: metricflow
  DB_USER: metricflow
  DB_PASSWORD: changeme
