apiVersion: v1
kind: ConfigMap
metadata:
  name: metricflow-config
  labels:
    app.kubernetes.io/name: metricflow
    app.kubernetes.io/component: api
data:
  DB_NAME: metricflow
  DB_HOST: postgres
  DB_PORT: "5432"
  SOURCE_URL: file:///migrations