name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '1.25'
            
            - name: Go vet
              run: go vet ./...

            - name: Go test
              run: go test -race ./...
            
            - name: vulncheck
              uses: golang/govulncheck-action@v1

            - name: gosec
              uses: securego/gosec@v2.26.1
              with:
                args: ./...

            - name: golang-ci
              uses: golangci/golangci-lint-action@v9
              with:
                version: latest